### PR TITLE
allow for saving modules without removing them from project

### PR DESCRIPTION
**Pull request by connerk**
export/import can be tedious and dangerous during development. this allows export for git diff without totally removing modules from the project

### CODE REVIEW

**Comment by mattpalermo** [comment]
Thankyou connerk for your contribution. I'll try get around to testing this as soon as possible. But in the mean time do you mind discussing this a little bit?

The reason why I never implemented this was because I thought it would be dangerous. If you 'save' then you end up with the code in 2 places. E.g. You could potentially do the following:

1. Save
2. Edit xlsm file
3. Import (loosing all your changes)

On further thought, this problem could be avoided by disabling Import until Export is used.

Do you think this concern is realistic or impractical?

Code looks great by the way. I'm assuming that you updated the xlsm with the ribbon.xml?

**Comment by connerk** [comment]
Hi Matt

I found myself hitting `export` immediately followed by `import` quite often, as I like to export modules quite frequently prior to running during development due Excel stability with some VBA/library errors.

good point about Save conflicting with Import. I like the idea of saving a state between `import/export`. `Workbook.CustomDocumentProperty()`? `Interaction.SaveSetting()`?

I've experienced an opposite issue from code in two places where we exported code, then checked it through git diff, made some sort of partial change and lost code that way. I don't remember the finite details, it was a couple weeks ago.
With Excel storing the modules inside the binary, we _always_ run the risk of it being different than what's exported to disk unless you `export` on `workbook_close` and `import` on `workbook_open` automatically and I don't want to install this tool for all my user's!

yes, the binary contains the ribbon.xml addition. I took liberty with changing some of the verbose text while in there. and you may prefer a different MsoIcon. just let me know and I'll correct it as instructed.

Thanks!

**Comment by mattpalermo** [comment]
Hi Kevin,

Sorry I deleted my previous comment. It's been some time since I've worked on this and I realised I was wrong about the current state of affairs protecting against loss of data. (A little bit tired atm)

Thankyou for your contribution. Your contribution looks great and I trust that it works just as expected.

With more thought, i think this will be a very convinent change. I think i'll return to this when I have access to a computer and some sleep.

Cheers, Matt

**Comment by mattpalermo** [comment]
Ok, I can think and work more clearly now.

I'd like to merge this feature. I can't test or build because I canceled my Excel license (Office365) while I'm not using it but I'd like use this feature myself when I do use it again. I'll update the README and changelog to reflect the changes. Would you be able to send me a built copy of the Add-in so I can upload it using GitHub releases?

> I found myself hitting export immediately followed by import quite often, as I like to export modules quite frequently prior to running during development due Excel stability with some VBA/library errors.

This is a good point. It always got me so infuriated when Excel would crash, so instead of just killing the program like a sane dev, I'd have to worry about what would happen to my source as well!

> I've experienced an opposite issue from code in two places where we exported code, then checked it through git diff, made some sort of partial change and lost code that way. I don't remember the finite details, it was a couple weeks ago.

Earlier I forgot that when you import the files in the file system remains there. This means that you can loose work from:

1. Import
2. Edit files in file system
3. Export

> With Excel storing the modules inside the binary, we always run the risk of it being different than what's exported to disk...

True. I suppose anyone using this should understand what they're doing anyway. But any way that we can minimize the chance for data loss is good because it's not a good feeling.

**Pull request merged**
